# Generated by Django 5.1.5 on 2025-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_score_basiccredits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='user',
            name='basicCredits',
            field=models.IntegerField(default=0),
        ),
    ]
