# Generated by Django 5.1.5 on 2025-02-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_delete_score_user_basiccredits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='basicCredits',
            new_name='basic_credits',
        ),
    ]
