# Generated by Django 5.1.5 on 2025-02-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_rename_basiccredits_user_basic_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basic_credits',
        ),
    ]
