# Generated by Django 5.1.5 on 2025-02-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_remove_user_basic_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_credits',
            field=models.IntegerField(default=0),
        ),
    ]
