# Generated by Django 5.1.5 on 2025-02-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_user_basic_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
