# Generated by Django 5.1.5 on 2025-02-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_remove_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basic_credits',
        ),
    ]
