# Generated by Django 5.1.5 on 2025-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_remove_user_basic_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('game_keeper', 'Game Keeper'), ('developer', 'Developer')], default='player', max_length=20),
        ),
    ]
