# Generated by Django 5.1.5 on 2025-02-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_user_basic_credits_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='basic_credits',
            new_name='score',
        ),
    ]
