# Generated by Django 5.1.5 on 2025-02-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_rename_basic_credits_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
    ]
